### ISSUE TITLE
Android Studio Flamingo & JDK 17

### ISSUE THREAD

**Issue by nicolasygrand** [faberNovel/docker-android#120]
Android Studio Flamingo is now stable and one of notable changes is [embedded JDK moved to 17](https://developer.android.com/studio/releases#jdk-17).

Currently, docker-android releases only bring JDK 8/11.

**Comment by sjcqs** [comment]
You can use `setup-java` to install the JDK 17

``` yaml
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '17'
```
